spring.application.name=BookingBackend
# Use the System Environment Variable names defined in docker-compose
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Serialize LocalDateTime as ISO-8601 strings (e.g. "2026-04-06T14:00:00") instead of arrays
spring.jackson.serialization.write-dates-as-timestamps=false

# FILE UPLOAD LIMITS
# Maximum size for a SINGLE file (Default is 1MB)
spring.servlet.multipart.max-file-size=10MB

# Maximum size for the ENTIRE request (All files combined + JSON) (Default is 10MB)
spring.servlet.multipart.max-request-size=50MB

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE